[workspace]
members = [
    "0-template",
    "1-echor",
    "2-catr",
    "3-headr",
    "4-wcr",
    "5-uniqr",
    "6-findr",
    "7-cutr",
    "8-grepr",
    "9-commr",
    "10-tailr",
    "11-fortuner",
]
resolver = "2"
